#version: 0.0
#Resources:
#  - TargetService:
#      Type: AWS::ECS::Service
#      Properties:
#        TaskDefinition: "arn:aws:ecs:eu-west-2:107404535822:task-definition/nginx-service-a:1"
#        LoadBalancerInfo:
#          ContainerName: "nginx-service-a-container"
#          ContainerPort: 8081
#        PlatformVersion: "LATEST"

applicationName: 'routercodedeployapp'
deploymentGroupName: 'routercodedeploygroup'
revision:
  revisionType: AppSpecContent
  appSpecContent:
    content: |
      version: 0.0
      Resources:
        - TargetService:
            Type: AWS::ECS::Service
            Properties:
              TaskDefinition: "arn:aws:ecs:eu-west-2:107404535822:task-definition/nginx-router:5"
              LoadBalancerInfo:
                ContainerName: "nginx-router-container"
                ContainerPort: 8080